### PR TITLE
Create RagAlley.json

### PR DESCRIPTION
**Pull request by arressaye**
Added RagAlley contract details

### CODE REVIEW

**Comment by clawoo** [comment]
Thanks for making the pr, looks good! Before merging, I noticed some time lock scripts that you also have. Basically, we can track those too depending what they are used for. Can you tell me if any of these scripts (or others) should be added to the json?

71864ad867a93c844024c8b5bcaa62b4cd0aee8599b9b665991620de34
717021b652efd8d48d172e07ef9cc2ad17ac4dc94b6abd0632390ea2e5
71630e855a6b565c7f161e57da604eaae74fef2edc83ff432334b7f083
718b2b34b4bd342d1674e560858f8f05532da9fdf273f5aabe983022f6
718d5551bb78f90d26ce064e7c69dd71d43626e242d0933e60b0bbaf4a
71cf197f1c2f560b654d8c4222ed583daf5f40dc72c377751e9eaccbd7
7108b9ebe0eb890e0d1cd27c8c8497be625eb31fb16da318cdd6a09458
71805884c1aec7965ff91e5fb28d73879c18012bf213b6be8c6164c00b
71dad483d3d87d002643721675b750e163cf1fbba6bcddbca7b952f569
7111bd192a88cf6767070da3793389567c60c694905492c0aa310d6a77
71204bfc1556a277908586cc1e46bb48678e506973927599ac80ba5a5b
71deb68ba32541b69c77236e7824fc641fe981a201e9fc52bfd97ba35d
Thanks!

**Comment by arressaye** [comment]
Those were embarrassing mistakes! I basically wanted to lock the SC once so I can use it repeatedly in reference inputs but accidentally re-ran the script several times so resulted in that many of the same script (and 180ADA!) locked at the SC address. I only use the one I specified in our reference inputs so there's no need to track the others. Thanks for bringing this up!

**Comment by arressaye** [comment]
Oh sorry I misunderstood your question. Those are actually multi-sig wallets I used in our auction system. These were created on-the-fly as and when a user puts in a bid, so there's no need to track them. We're also going to change the auction system to a SC one, and I'll update the JSON once the auction SC is completed. Thanks again!

**Comment by clawoo** [comment]
Got it! Ok, thanks for the info. Congrats for the launch!

**Pull request merged**
